name: Update NSE Stocks

on:
  workflow_dispatch:

  schedule:
    - cron: "30 18 * * 1-5"

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Libraries
        run: |
          pip install -r requirements.txt

      - name: Run Python Script
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          python update_sheet.py
